Repository apple/swift-nio-ssh, pull requests merged in 2021-03, with the labels that each got.

#77 fix doc generation script
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#76 Adds emittion of user authentication success event.
  Sources/NIOSSH/Connection State Machine/Operations/AcceptsUserAuthMessages.swift
  Sources/NIOSSH/Connection State Machine/SSHConnectionStateMachine.swift
  Sources/NIOSSH/NIOSSHHandler.swift
  Tests/NIOSSHTests/EndToEndTests.swift
  Tests/NIOSSHTests/SSHConnectionStateMachineTests.swift
Labels: 🔼 needs-minor-version-bump

#78 Docker setup for main nightlies
  docker/docker-compose.2004.main.yaml
Labels: needs-no-version-bump

#79 Add SECURITY.md
  SECURITY.md
Labels: needs-no-version-bump

#80 Add support from synchronous options
  Package.swift
  Sources/NIOSSH/Child Channels/SSHChildChannel.swift
  Tests/NIOSSHTests/ChildChannelMultiplexerTests.swift
Labels: patch-version-bump-only
