Repository apple/swift-nio-ssh, pull requests merged in 2022-04, with the labels that each got.

#109 Support identification string without carriage return
  Sources/NIOSSH/SSHPacketParser.swift
  Tests/NIOSSHTests/SSHPacketParserTests.swift
Labels: patch-version-bump-only

#111 Add API breakages script from NIO
  scripts/check_no_api_breakages.sh
Labels: needs-no-version-bump

#113 Drop support for Swift 5.2 and 5.3
  Package.swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1604.53.yaml
  docker/docker-compose.1804.52.yaml
  docker/docker-compose.1804.54.yaml
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump
