Repository apple/swift-nio-ssh, pull requests merged in 2025-03, with the labels that each got.

#190 Rename nightly_6_1 params to nightly_next
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#191 move nightly-next thresholds and add legacy symlink
  Benchmarks/Thresholds/nightly-6.1
  Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.ManySmallCommandsPerConnection.p90.json
  Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.OneCommandPerConnection.p90.json
  Benchmarks/Thresholds/nightly-next/NIOSSHBenchmarks.StreamingLargeMessageInSmallChunks.p90.json
Labels: semver/none

#192 Delete Thresholds/nightly-6.1 symlink
  Benchmarks/Thresholds/nightly-6.1
Labels: semver/none

#193 Only apply standard swift settings on valid targets
  Package.swift
Labels: semver/none

#195 Get handler from correct channel in tests
  Tests/NIOSSHTests/EndToEndTests.swift
Labels: semver/none

#196 Strict concurrency for NIOSSH
  Package.swift
  Sources/NIOSSH/Child Channels/ChildChannelOptions.swift
  Sources/NIOSSH/Child Channels/ChildChannelUserEvents.swift
  Sources/NIOSSH/Child Channels/SSHChildChannel.swift
  Sources/NIOSSH/GlobalRequestDelegate.swift
  Sources/NIOSSH/NIOSSHHandler.swift
  Sources/NIOSSH/Role.swift
  Sources/NIOSSH/SSHClientConfiguration.swift
  Sources/NIOSSH/SSHServerConfiguration.swift
  Sources/NIOSSH/User Authentication/ClientUserAuthenticationDelegate.swift
Labels: 🆕 semver/minor

#197 Strict concurrency for SSHClient and perf tester
  Package.swift
  Sources/NIOSSHClient/ExecHandler.swift
  Sources/NIOSSHClient/InteractivePasswordPromptDelegate.swift
  Sources/NIOSSHClient/PortForwardingServer.swift
  Sources/NIOSSHClient/main.swift
  Sources/NIOSSHPerformanceTester/BenchmarkHandshake.swift
  Sources/NIOSSHPerformanceTester/BenchmarkLinearThroughput.swift
Labels: 🔨 semver/patch

#199 Enable macOS CI on merge to main and daily timer
  .github/workflows/main.yml
Labels: semver/none

#200 Marks SSHChannelData as sendable
  Sources/NIOSSH/Child Channels/SSHChannelData.swift
Labels: 🔨 semver/patch
